// Shared catalog of LLM providers and their supported models.
// Used to render dropdowns on the web + mobile API-key settings so users can
// pick a provider/model instead of typing IDs by hand.
// Model IDs are the exact IDs the provider accepts via /v1/chat/completions.

export interface LLMModelOption {
  value: string
  label: string
}

export interface LLMProviderOption {
  value: string
  label: string
  apiKeyField: "OPENAI_API_KEY" | "ANTHROPIC_API_KEY" | "OPENCODE_API_KEY"
  baseUrl: string // OpenAI-compatible base URL; "" means provider-native default
  defaultModel: string
  models: LLMModelOption[]
  description: string
}

export const LLM_PROVIDERS: LLMProviderOption[] = [
  {
    value: "openai",
    label: "OpenAI",
    apiKeyField: "OPENAI_API_KEY",
    baseUrl: "",
    defaultModel: "gpt-5.4-mini",
    description: "Frontier proprietary models (GPT-5.x, GPT-4o, o-series reasoning).",
    models: [
      { value: "gpt-5.6-sol", label: "GPT-5.6 Sol" },
      { value: "gpt-5.6-terra", label: "GPT-5.6 Terra" },
      { value: "gpt-5.6-luna", label: "GPT-5.6 Luna" },
      { value: "gpt-5.5", label: "GPT-5.5" },
      { value: "gpt-5.5-pro", label: "GPT-5.5 Pro" },
      { value: "gpt-5.4", label: "GPT-5.4" },
      { value: "gpt-5.4-pro", label: "GPT-5.4 Pro" },
      { value: "gpt-5.4-mini", label: "GPT-5.4 mini" },
      { value: "gpt-5.4-nano", label: "GPT-5.4 nano" },
      { value: "gpt-5.3-codex-spark", label: "GPT-5.3 Codex Spark" },
      { value: "gpt-5.3-codex", label: "GPT-5.3 Codex" },
      { value: "gpt-5.2", label: "GPT-5.2" },
      { value: "gpt-5.2-codex", label: "GPT-5.2 Codex" },
      { value: "gpt-5.1", label: "GPT-5.1" },
      { value: "gpt-5.1-codex-max", label: "GPT-5.1 Codex Max" },
      { value: "gpt-5.1-codex", label: "GPT-5.1 Codex" },
      { value: "gpt-5.1-codex-mini", label: "GPT-5.1 Codex Mini" },
      { value: "gpt-5", label: "GPT-5" },
      { value: "gpt-5-codex", label: "GPT-5 Codex" },
      { value: "gpt-5-nano", label: "GPT-5 nano" },
      { value: "gpt-4.1", label: "GPT-4.1" },
      { value: "gpt-4.1-mini", label: "GPT-4.1 mini" },
      { value: "gpt-4.1-nano", label: "GPT-4.1 nano" },
      { value: "gpt-4o", label: "GPT-4o" },
      { value: "gpt-4o-mini", label: "GPT-4o mini" },
      { value: "o3", label: "o3 (reasoning)" },
      { value: "o3-mini", label: "o3-mini (reasoning)" },
      { value: "o4-mini", label: "o4-mini (reasoning)" },
    ],
  },
  {
    value: "claude",
    label: "Anthropic Claude",
    apiKeyField: "ANTHROPIC_API_KEY",
    baseUrl: "",
    defaultModel: "claude-haiku-4-5",
    description: "Claude Opus / Sonnet / Haiku. Strong reasoning & long context.",
    models: [
      { value: "claude-fable-5", label: "Claude Fable 5" },
      { value: "claude-opus-5", label: "Claude Opus 5" },
      { value: "claude-opus-4-8", label: "Claude Opus 4.8" },
      { value: "claude-opus-4-7", label: "Claude Opus 4.7" },
      { value: "claude-opus-4-6", label: "Claude Opus 4.6" },
      { value: "claude-opus-4-5", label: "Claude Opus 4.5" },
      { value: "claude-sonnet-5", label: "Claude Sonnet 5" },
      { value: "claude-sonnet-4-6", label: "Claude Sonnet 4.6" },
      { value: "claude-sonnet-4-5", label: "Claude Sonnet 4.5" },
      { value: "claude-sonnet-4", label: "Claude Sonnet 4" },
      { value: "claude-haiku-4-5", label: "Claude Haiku 4.5" },
    ],
  },
  {
    value: "google",
    label: "Google Gemini",
    apiKeyField: "OPENAI_API_KEY",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai",
    defaultModel: "gemini-3.7-flash",
    description: "Gemini via OpenAI-compatible endpoint.",
    models: [
      { value: "gemini-3.7-flash", label: "Gemini 3.7 Flash" },
      { value: "gemini-3.6-flash", label: "Gemini 3.6 Flash" },
      { value: "gemini-3.5-flash", label: "Gemini 3.5 Flash" },
      { value: "gemini-3.5-flash-lite", label: "Gemini 3.5 Flash-Lite" },
      { value: "gemini-3.1-pro", label: "Gemini 3.1 Pro" },
      { value: "gemini-3-flash", label: "Gemini 3 Flash" },
      { value: "gemini-2.5-pro", label: "Gemini 2.5 Pro" },
      { value: "gemini-2.5-flash", label: "Gemini 2.5 Flash" },
      { value: "gemini-2.5-flash-lite", label: "Gemini 2.5 Flash-Lite" },
      { value: "gemini-2.0-flash", label: "Gemini 2.0 Flash" },
      { value: "gemini-1.5-pro", label: "Gemini 1.5 Pro" },
      { value: "gemini-1.5-flash", label: "Gemini 1.5 Flash" },
    ],
  },
  {
    value: "groq",
    label: "Groq",
    apiKeyField: "OPENAI_API_KEY",
    baseUrl: "https://api.groq.com/openai/v1",
    defaultModel: "llama-3.3-70b-versatile",
    description: "Ultra-fast inference (LPUs). Open-weight models, very cheap.",
    models: [
      { value: "llama-3.3-70b-versatile", label: "Llama 3.3 70B Versatile" },
      { value: "llama-3.1-8b-instant", label: "Llama 3.1 8B Instant" },
      { value: "llama-3.1-70b-versatile", label: "Llama 3.1 70B Versatile" },
      { value: "llama-4-scout-17b-16e-instruct", label: "Llama 4 Scout" },
      { value: "llama-4-maverick-17b-128e-instruct", label: "Llama 4 Maverick" },
      { value: "openai/gpt-oss-20b", label: "GPT-OSS-20B" },
      { value: "openai/gpt-oss-120b", label: "GPT-OSS-120B" },
      { value: "qwen-3-32b", label: "Qwen3 32B" },
      { value: "qwen-3-8b", label: "Qwen3 8B" },
      { value: "gemma-2-27b", label: "Gemma 2 27B" },
      { value: "gemma-2-9b", label: "Gemma 2 9B" },
      { value: "deepseek-r1-distill-llama-70b", label: "DeepSeek R1 Distill 70B" },
    ],
  },
  {
    value: "cerebras",
    label: "Cerebras",
    apiKeyField: "OPENAI_API_KEY",
    baseUrl: "https://api.cerebras.ai/v1",
    defaultModel: "gpt-oss-120b",
    description: "Highest sustained throughput (WSE). Small curated catalog.",
    models: [
      { value: "gpt-oss-120b", label: "GPT-OSS-120B" },
      { value: "gpt-oss-20b", label: "GPT-OSS-20B" },
      { value: "llama-3.3-70b", label: "Llama 3.3 70B" },
      { value: "llama-3.1-70b", label: "Llama 3.1 70B" },
      { value: "llama-3.1-8b", label: "Llama 3.1 8B" },
      { value: "qwen-3-32b", label: "Qwen3 32B" },
      { value: "qwen-3-8b", label: "Qwen3 8B" },
    ],
  },
  {
    value: "openrouter",
    label: "OpenRouter",
    apiKeyField: "OPENAI_API_KEY",
    baseUrl: "https://openrouter.ai/api/v1",
    defaultModel: "openai/gpt-4o-mini",
    description: "One API across many providers; routes to cheapest/fastest.",
    models: [
      { value: "openai/gpt-5.5", label: "GPT-5.5" },
      { value: "openai/gpt-5", label: "GPT-5" },
      { value: "openai/gpt-5-nano", label: "GPT-5 nano" },
      { value: "openai/gpt-4o", label: "GPT-4o" },
      { value: "openai/gpt-4o-mini", label: "GPT-4o mini" },
      { value: "openai/o3-mini", label: "o3-mini" },
      { value: "openai/o4-mini", label: "o4-mini" },
      { value: "anthropic/claude-sonnet-4-6", label: "Claude Sonnet 4.6" },
      { value: "anthropic/claude-sonnet-4-5", label: "Claude Sonnet 4.5" },
      { value: "anthropic/claude-opus-4-6", label: "Claude Opus 4.6" },
      { value: "anthropic/claude-haiku-4-5", label: "Claude Haiku 4.5" },
      { value: "google/gemini-3.7-flash", label: "Gemini 3.7 Flash" },
      { value: "google/gemini-3.1-pro", label: "Gemini 3.1 Pro" },
      { value: "google/gemini-2.5-flash", label: "Gemini 2.5 Flash" },
      { value: "deepseek/deepseek-chat", label: "DeepSeek V3" },
      { value: "deepseek/deepseek-reasoner", label: "DeepSeek R1" },
      { value: "deepseek/deepseek-v4-flash", label: "DeepSeek V4 Flash" },
      { value: "meta-llama/llama-4-maverick", label: "Llama 4 Maverick" },
      { value: "meta-llama/llama-4-scout", label: "Llama 4 Scout" },
      { value: "mistralai/mistral-large-latest", label: "Mistral Large" },
      { value: "qwen/qwen-3-32b", label: "Qwen3 32B" },
      { value: "x-ai/grok-4-fast", label: "Grok 4 Fast" },
      { value: "minimax/minimax-m3", label: "MiniMax M3" },
      { value: "kimi/kimi-k2.7-code", label: "Kimi K2.7 Code" },
    ],
  },
  {
    value: "deepseek",
    label: "DeepSeek",
    apiKeyField: "OPENAI_API_KEY",
    baseUrl: "https://api.deepseek.com/v1",
    defaultModel: "deepseek-chat",
    description: "Ultra-low-cost frontier-quality models.",
    models: [
      { value: "deepseek-chat", label: "DeepSeek V3 (chat)" },
      { value: "deepseek-reasoner", label: "DeepSeek R1 (reasoning)" },
      { value: "deepseek-v4-pro", label: "DeepSeek V4 Pro" },
      { value: "deepseek-v4-flash", label: "DeepSeek V4 Flash" },
      { value: "deepseek-coder", label: "DeepSeek Coder" },
      { value: "deepseek-r1-0528", label: "DeepSeek R1-0528" },
      { value: "deepseek-v3.1", label: "DeepSeek V3.1" },
      { value: "deepseek-v3-0324", label: "DeepSeek V3-0324" },
    ],
  },
  {
    value: "mistral",
    label: "Mistral AI",
    apiKeyField: "OPENAI_API_KEY",
    baseUrl: "https://api.mistral.ai/v1",
    defaultModel: "mistral-small-latest",
    description: "EU-hosted open-weight models; very affordable.",
    models: [
      { value: "mistral-large-latest", label: "Mistral Large" },
      { value: "mistral-medium-latest", label: "Mistral Medium" },
      { value: "mistral-small-latest", label: "Mistral Small" },
      { value: "mistral-nemo", label: "Mistral Nemo" },
      { value: "ministral-3b", label: "Ministral 3B" },
      { value: "ministral-8b", label: "Ministral 8B" },
      { value: "codestral-latest", label: "Codestral" },
      { value: "pixtral-large-latest", label: "Pixtral Large" },
      { value: "pixtral-12b", label: "Pixtral 12B" },
      { value: "open-mistral-nemo", label: "Open Mistral Nemo" },
      { value: "open-mixtral-8x22b", label: "Mixtral 8x22B" },
    ],
  },
  {
    value: "deepinfra",
    label: "DeepInfra",
    apiKeyField: "OPENAI_API_KEY",
    baseUrl: "https://api.deepinfra.com/v1/openai",
    defaultModel: "meta-llama/Llama-3.3-70B-Instruct",
    description: "Low-cost open-weight inference, huge catalog.",
    models: [
      { value: "meta-llama/Llama-3.3-70B-Instruct", label: "Llama 3.3 70B Instruct" },
      { value: "meta-llama/Llama-4-Maverick", label: "Llama 4 Maverick" },
      { value: "meta-llama/Llama-4-Scout", label: "Llama 4 Scout" },
      { value: "meta-llama/Llama-3.1-405B-Instruct", label: "Llama 3.1 405B" },
      { value: "Qwen/Qwen2.5-72B-Instruct", label: "Qwen 2.5 72B" },
      { value: "Qwen/Qwen3-32B", label: "Qwen3 32B" },
      { value: "deepseek-ai/DeepSeek-V3", label: "DeepSeek V3" },
      { value: "deepseek-ai/DeepSeek-R1", label: "DeepSeek R1" },
      { value: "google/gemma-2-27b-it", label: "Gemma 2 27B IT" },
      { value: "mistralai/Mixtral-8x22B-Instruct-v0.1", label: "Mixtral 8x22B" },
    ],
  },
  {
    value: "together",
    label: "Together AI",
    apiKeyField: "OPENAI_API_KEY",
    baseUrl: "https://api.together.xyz/v1",
    defaultModel: "meta-llama/Meta-Llama-3.3-70B-Instruct-Turbo",
    description: "Open-weight models + fine-tuning.",
    models: [
      { value: "meta-llama/Meta-Llama-3.3-70B-Instruct-Turbo", label: "Llama 3.3 70B Turbo" },
      { value: "meta-llama/Llama-4-Maverick", label: "Llama 4 Maverick" },
      { value: "meta-llama/Llama-4-Scout", label: "Llama 4 Scout" },
      { value: "meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo", label: "Llama 3.1 405B Turbo" },
      { value: "deepseek-ai/DeepSeek-V3", label: "DeepSeek V3" },
      { value: "deepseek-ai/DeepSeek-R1", label: "DeepSeek R1" },
      { value: "Qwen/Qwen2.5-72B-Instruct", label: "Qwen 2.5 72B" },
      { value: "Qwen/Qwen3-32B", label: "Qwen3 32B" },
      { value: "google/gemma-2-27b-it", label: "Gemma 2 27B IT" },
      { value: "mistralai/Mixtral-8x22B-Instruct-v0.1", label: "Mixtral 8x22B" },
    ],
  },
  {
    value: "xai",
    label: "xAI Grok",
    apiKeyField: "OPENAI_API_KEY",
    baseUrl: "https://api.x.ai/v1",
    defaultModel: "grok-4-fast",
    description: "Grok 4 via OpenAI-compatible API.",
    models: [
      { value: "grok-4.6", label: "Grok 4.6" },
      { value: "grok-4.5", label: "Grok 4.5" },
      { value: "grok-4", label: "Grok 4" },
      { value: "grok-4-fast", label: "Grok 4 Fast" },
      { value: "grok-4-mini", label: "Grok 4 mini" },
      { value: "grok-3", label: "Grok 3" },
      { value: "grok-3-fast", label: "Grok 3 Fast" },
      { value: "grok-3-mini", label: "Grok 3 mini" },
      { value: "grok-2", label: "Grok 2" },
      { value: "grok-build-0.1", label: "Grok Build 0.1" },
    ],
  },
  {
    value: "opencode",
    label: "OpenCode Zen",
    apiKeyField: "OPENCODE_API_KEY",
    baseUrl: "https://opencode.ai/zen/v1",
    defaultModel: "gpt-5.4-mini",
    description: "Curated gateway from the OpenCode team — GPT, Claude, Gemini, DeepSeek, Kimi, MiniMax, GLM & free models via one key.",
    models: [
      { value: "gpt-5.6-sol", label: "GPT-5.6 Sol" },
      { value: "gpt-5.6-terra", label: "GPT-5.6 Terra" },
      { value: "gpt-5.6-luna", label: "GPT-5.6 Luna" },
      { value: "gpt-5.5", label: "GPT-5.5" },
      { value: "gpt-5.5-pro", label: "GPT-5.5 Pro" },
      { value: "gpt-5.4", label: "GPT-5.4" },
      { value: "gpt-5.4-pro", label: "GPT-5.4 Pro" },
      { value: "gpt-5.4-mini", label: "GPT-5.4 mini" },
      { value: "gpt-5.4-nano", label: "GPT-5.4 nano" },
      { value: "gpt-5.3-codex-spark", label: "GPT-5.3 Codex Spark" },
      { value: "gpt-5.3-codex", label: "GPT-5.3 Codex" },
      { value: "gpt-5.2", label: "GPT-5.2" },
      { value: "gpt-5.2-codex", label: "GPT-5.2 Codex" },
      { value: "gpt-5.1", label: "GPT-5.1" },
      { value: "gpt-5.1-codex-max", label: "GPT-5.1 Codex Max" },
      { value: "gpt-5.1-codex", label: "GPT-5.1 Codex" },
      { value: "gpt-5.1-codex-mini", label: "GPT-5.1 Codex Mini" },
      { value: "gpt-5", label: "GPT-5" },
      { value: "gpt-5-codex", label: "GPT-5 Codex" },
      { value: "gpt-5-nano", label: "GPT-5 nano" },
      { value: "claude-fable-5", label: "Claude Fable 5" },
      { value: "claude-opus-5", label: "Claude Opus 5" },
      { value: "claude-opus-4-8", label: "Claude Opus 4.8" },
      { value: "claude-opus-4-7", label: "Claude Opus 4.7" },
      { value: "claude-opus-4-6", label: "Claude Opus 4.6" },
      { value: "claude-opus-4-5", label: "Claude Opus 4.5" },
      { value: "claude-sonnet-5", label: "Claude Sonnet 5" },
      { value: "claude-sonnet-4-6", label: "Claude Sonnet 4.6" },
      { value: "claude-sonnet-4-5", label: "Claude Sonnet 4.5" },
      { value: "claude-sonnet-4", label: "Claude Sonnet 4" },
      { value: "claude-haiku-4-5", label: "Claude Haiku 4.5" },
      { value: "gemini-3.7-flash", label: "Gemini 3.7 Flash" },
      { value: "gemini-3.6-flash", label: "Gemini 3.6 Flash" },
      { value: "gemini-3.5-flash", label: "Gemini 3.5 Flash" },
      { value: "gemini-3.5-flash-lite", label: "Gemini 3.5 Flash-Lite" },
      { value: "gemini-3.1-pro", label: "Gemini 3.1 Pro" },
      { value: "gemini-3-flash", label: "Gemini 3 Flash" },
      { value: "deepseek-v4-pro", label: "DeepSeek V4 Pro" },
      { value: "deepseek-v4-flash", label: "DeepSeek V4 Flash" },
      { value: "glm-5.2", label: "GLM 5.2" },
      { value: "glm-5.1", label: "GLM 5.1" },
      { value: "glm-5", label: "GLM 5" },
      { value: "minimax-m3", label: "MiniMax M3" },
      { value: "minimax-m2.7", label: "MiniMax M2.7" },
      { value: "minimax-m2.5", label: "MiniMax M2.5" },
      { value: "kimi-k3", label: "Kimi K3" },
      { value: "kimi-k2.7-code", label: "Kimi K2.7 Code" },
      { value: "kimi-k2.6", label: "Kimi K2.6" },
      { value: "kimi-k2.5", label: "Kimi K2.5" },
      { value: "qwen3.6-plus", label: "Qwen3.6 Plus" },
      { value: "qwen3.5-plus", label: "Qwen3.5 Plus" },
      { value: "big-pickle", label: "Big Pickle" },
      { value: "grok-4.6", label: "Grok 4.6" },
      { value: "grok-4.5", label: "Grok 4.5" },
      { value: "grok-build-0.1", label: "Grok Build 0.1" },
      { value: "muse-spark-1.2", label: "Muse Spark 1.2" },
      { value: "deepseek-v4-flash-free", label: "DeepSeek V4 Flash (free)" },
      { value: "mimo-v2.5-free", label: "MiMo V2.5 (free)" },
      { value: "hy3-free", label: "Hy3 (free)" },
      { value: "nemotron-3-ultra-free", label: "Nemotron 3 Ultra (free)" },
      { value: "nemotron-3.5-lightning-free", label: "Nemotron 3.5 Lightning (free)" },
      { value: "laguna-s-2.1-free", label: "Laguna S 2.1 (free)" },
    ],
  },
  {
    value: "local",
    label: "Local LLM (Ollama / LM Studio)",
    apiKeyField: "OPENAI_API_KEY",
    baseUrl: "http://localhost:11434/v1",
    defaultModel: "llama3.1",
    description: "Free local models. Set the endpoint below (Ollama or LM Studio).",
    models: [
      { value: "llama3.1", label: "Llama 3.1 (Ollama)" },
      { value: "llama3.2", label: "Llama 3.2 (Ollama)" },
      { value: "llama3", label: "Llama 3 (Ollama)" },
      { value: "llama2", label: "Llama 2 (Ollama)" },
      { value: "mistral", label: "Mistral (Ollama)" },
      { value: "qwen2.5", label: "Qwen 2.5 (Ollama)" },
      { value: "qwen2.5-coder", label: "Qwen 2.5 Coder (Ollama)" },
      { value: "gemma2", label: "Gemma 2 (Ollama)" },
      { value: "gemma3", label: "Gemma 3 (Ollama)" },
      { value: "phi4", label: "Phi-4 (Ollama)" },
      { value: "deepseek-r1", label: "DeepSeek R1 (Ollama)" },
      { value: "deepseek-v3", label: "DeepSeek V3 (Ollama)" },
      { value: "codellama", label: "CodeLlama (Ollama)" },
      { value: "starcoder2", label: "StarCoder2 (Ollama)" },
    ],
  },
]

export function getProvider(value?: string): LLMProviderOption | undefined {
  return LLM_PROVIDERS.find((p) => p.value === value)
}

export function defaultModelFor(value?: string): string {
  return getProvider(value)?.defaultModel || "gpt-4o-mini"
}

export function providerDefaultBaseUrl(value?: string): string {
  return getProvider(value)?.baseUrl || ""
}

export function providerApiKeyField(value?: string): string {
  return getProvider(value)?.apiKeyField || "OPENAI_API_KEY"
}

export function providerLabel(value?: string): string {
  return getProvider(value)?.label || value || ""
}
