// PeteMart Mock Data - Dummy data for UI development and testing
// This provides realistic data for all screens across Customer, Merchant, and Admin personas

import { Market, Merchant, Product, Order, CartItem, Address } from './supabase';

export const MARKETS: Market[] = [
  {
    id: 'market-1',
    name: 'Chickpet',
    slug: 'chickpet',
    description: 'The Textile Heart of Bangalore',
    specialization: 'Textiles, Silk, Sarees',
    historical_summary: 'One of Bangalore\'s oldest markets, Chickpet has been the textile hub for over a century. Known for its narrow lanes lined with shops selling everything from Kanjivaram silk to cotton fabrics.',
    image_url: '/images/markets/chickpet.jpg',
    merchant_count: 118,
  },
  {
    id: 'market-2',
    name: 'Balepet',
    slug: 'balepet',
    description: 'Household & Everyday Essentials',
    specialization: 'Household, Florists, Bakery, Textiles',
    historical_summary: 'Balepet market dates back to the early 1900s and serves as the neighborhood hub for daily essentials, fresh flowers, and traditional textiles.',
    image_url: '/images/markets/balepet.jpg',
    merchant_count: 85,
  },
  {
    id: 'market-3',
    name: 'Raja Market',
    slug: 'raja-market',
    description: 'Jewellery & Traditional Crafts',
    specialization: 'Jewellery, Gold, Silver, Crafts',
    historical_summary: 'Raja Market is synonymous with fine jewellery and traditional crafts. Established in the 1940s, it houses generations of master jewellers and craftsmen.',
    image_url: '/images/markets/raja-market.jpg',
    merchant_count: 62,
  },
  {
    id: 'market-4',
    name: 'Mamulpet',
    slug: 'mamulpet',
    description: 'Wholesale & Bulk Goods',
    specialization: 'Wholesale, Spices, Dry Fruits',
    historical_summary: 'Mamulpet has been the wholesale backbone of Bangalore for generations, supplying spices, dry fruits, and bulk provisions across the city.',
    image_url: '/images/markets/mamulpet.jpg',
    merchant_count: 94,
  },
  {
    id: 'market-5',
    name: 'Cubbonpet',
    slug: 'cubbonpet',
    description: 'Electronics & Hardware',
    specialization: 'Electronics, Hardware, Tools',
    historical_summary: 'Named after Sir Mark Cubbon, this market district has evolved from a general trading hub to a specialized electronics and hardware market.',
    image_url: '/images/markets/cubbonpet.jpg',
    merchant_count: 73,
  },
];

export const MERCHANTS: Merchant[] = [
  {
    id: 'merchant-1',
    user_id: 'merch-001',
    store_name: 'Samskruti Silks',
    slug: 'samskruti-silks',
    market_id: 'market-1',
    category: 'Silk Sarees',
    description: 'Premium silk sarees with 18 years of tradition. Specializing in Kanjivaram, Mysore Silk, and handloom collections.',
    logo_url: '/images/merchants/samskruti-logo.jpg',
    banner_url: '/images/merchants/samskruti-banner.jpg',
    business_hours: { 'Mon-Sat': '10:00 AM - 8:00 PM', 'Sun': '11:00 AM - 6:00 PM' },
    modes_enabled: ['A', 'B', 'C'],
    status: 'active',
    rating: 4.8,
    distance: 2.3,
    digital_readiness: 'Medium',
  },
  {
    id: 'merchant-2',
    user_id: 'merch-001',
    store_name: 'Samskruti Silks (Branch)',
    slug: 'samskruti-silks-branch',
    market_id: 'market-1',
    category: 'Silk Sarees',
    description: 'Branch store of Samskruti Silks with exclusive collections.',
    logo_url: '/images/merchants/samskruti-logo.jpg',
    banner_url: '/images/merchants/samskruti-banner.jpg',
    business_hours: { 'Mon-Sat': '10:00 AM - 8:00 PM', 'Sun': '11:00 AM - 6:00 PM' },
    modes_enabled: ['A', 'B', 'C'],
    status: 'active',
    rating: 4.7,
    distance: 2.5,
    digital_readiness: 'Medium',
  },
  {
    id: 'merchant-3',
    user_id: 'merch-002',
    store_name: 'The Pastry Cafe',
    slug: 'pastry-cafe',
    market_id: 'market-2',
    category: 'Bakery & Cafe',
    description: 'Artisanal bakery crafting fresh pastries, cakes, and savories daily. A Balepet institution since 2005.',
    logo_url: '/images/merchants/pastry-logo.jpg',
    banner_url: '/images/merchants/pastry-banner.jpg',
    business_hours: { 'Mon-Sun': '7:00 AM - 9:00 PM' },
    modes_enabled: ['A', 'C'],
    status: 'active',
    rating: 4.5,
    distance: 3.1,
    digital_readiness: 'Medium',
  },
  {
    id: 'merchant-4',
    user_id: 'merch-003',
    store_name: 'flowers2u',
    slug: 'flowers2u',
    market_id: 'market-2',
    category: 'Florist & Fresh Flowers',
    description: 'Fresh cut flowers, bouquets, and floral arrangements for every occasion. Daily delivery across Bangalore.',
    logo_url: '/images/merchants/flowers-logo.jpg',
    banner_url: '/images/merchants/flowers-banner.jpg',
    business_hours: { 'Mon-Sun': '6:00 AM - 8:00 PM' },
    modes_enabled: ['A', 'B'],
    status: 'active',
    rating: 4.3,
    distance: 2.8,
    digital_readiness: 'Low',
  },
  {
    id: 'merchant-5',
    user_id: 'merch-004',
    store_name: 'Tarun Enterprises',
    slug: 'tarun-enterprises',
    market_id: 'market-1',
    category: 'Textiles Wholesale',
    description: 'Wholesale textile supplier specializing in bulk fabrics and garment materials since 1998.',
    logo_url: '/images/merchants/tarun-logo.jpg',
    banner_url: '/images/merchants/tarun-banner.jpg',
    business_hours: { 'Mon-Sat': '9:00 AM - 7:00 PM', 'Sun': 'Closed' },
    modes_enabled: ['B', 'C'],
    status: 'active',
    rating: 4.1,
    distance: 1.8,
    digital_readiness: 'Low',
  },
  {
    id: 'merchant-6',
    user_id: 'merch-005',
    store_name: 'Sri Vinayaka Textorium',
    slug: 'sri-vinayaka-textorium',
    market_id: 'market-2',
    category: 'Textiles & Fabrics',
    description: 'Traditional textile store offering a wide range of fabrics, suit lengths, and dress materials.',
    logo_url: '/images/merchants/vinayaka-logo.jpg',
    banner_url: '/images/merchants/vinayaka-banner.jpg',
    business_hours: { 'Mon-Sat': '10:00 AM - 8:30 PM', 'Sun': '11:00 AM - 5:00 PM' },
    modes_enabled: ['B', 'C'],
    status: 'active',
    rating: 4.2,
    distance: 3.4,
    digital_readiness: 'Low',
  },
  {
    id: 'merchant-7',
    user_id: 'merch-006',
    store_name: 'Sanjana Apparels (India)',
    slug: 'sanjana-apparels',
    market_id: 'market-2',
    category: 'Apparel & Clothing',
    description: 'Modern and traditional apparel for men, women, and children. Quality clothing at affordable prices.',
    logo_url: '/images/merchants/sanjana-logo.jpg',
    banner_url: '/images/merchants/sanjana-banner.jpg',
    business_hours: { 'Mon-Sat': '10:00 AM - 9:00 PM', 'Sun': '10:00 AM - 6:00 PM' },
    modes_enabled: ['A', 'B', 'C'],
    status: 'active',
    rating: 4.4,
    distance: 3.6,
    digital_readiness: 'Medium',
  },
  {
    id: 'merchant-8',
    user_id: 'merch-007',
    store_name: 'Madhumathi All-men\'s Ethnic',
    slug: 'madhumathi-ethnic',
    market_id: 'market-2',
    category: "Men's Ethnic Wear",
    description: "Specialized men's ethnic wear including kurtas, sherwanis, and wedding collections.",
    logo_url: '/images/merchants/madhumathi-logo.jpg',
    banner_url: '/images/merchants/madhumathi-banner.jpg',
    business_hours: { 'Mon-Sat': '10:00 AM - 8:00 PM', 'Sun': '11:00 AM - 5:00 PM' },
    modes_enabled: ['A', 'B', 'C'],
    status: 'pending',
    rating: 4.0,
    distance: 2.9,
    digital_readiness: 'Low',
  },
  {
    id: 'merchant-9',
    user_id: 'merch-008',
    store_name: 'Sri Vari Traders',
    slug: 'sri-vari-traders',
    market_id: 'market-2',
    category: 'Outdoor Equipment',
    description: 'Quality outdoor and camping equipment supplier serving Bangalore adventurers.',
    logo_url: '/images/merchants/srivari-logo.jpg',
    banner_url: '/images/merchants/srivari-banner.jpg',
    business_hours: { 'Mon-Sat': '9:30 AM - 7:30 PM', 'Sun': 'Closed' },
    modes_enabled: ['A', 'B'],
    status: 'pending',
    rating: 4.0,
    distance: 3.2,
    digital_readiness: 'Low',
  },
];

export const PRODUCTS: Product[] = [
  // Samskruti Silks Products
  {
    id: 'prod-001',
    merchant_id: 'merchant-1',
    merchant_name: 'Samskruti Silks',
    name: 'Kanjivaram Silk Saree - Gold Zari',
    description: 'Authentic Kanjivaram silk saree woven with pure gold zari. Features intricate temple border designs with traditional motifs. Perfect for weddings and festive occasions.',
    price: 32500,
    mrp: 35000,
    stock_count: 15,
    images: ['/images/products/saree-1.jpg', '/images/products/saree-2.jpg'],
    category: 'Silk Sarees',
    mode_badges: ['A', 'B', 'C'],
    sku: 'SS-SILK-001',
    rating: 4.8,
    review_count: 23,
    is_active: true,
  },
  {
    id: 'prod-002',
    merchant_id: 'merchant-1',
    merchant_name: 'Samskruti Silks',
    name: 'Mysore Silk Saree - Cream with Gold Border',
    description: 'Elegant Mysore silk saree in cream with traditional gold border. Lightweight and perfect for daily wear or casual events.',
    price: 8500,
    mrp: 9500,
    stock_count: 28,
    images: ['/images/products/mysore-silk.jpg'],
    category: 'Silk Sarees',
    mode_badges: ['A', 'B', 'C'],
    sku: 'SS-MS-002',
    rating: 4.6,
    review_count: 15,
    is_active: true,
  },
  {
    id: 'prod-003',
    merchant_id: 'merchant-1',
    merchant_name: 'Samskruti Silks',
    name: 'Cotton Silk Blend - Printed',
    description: 'Comfortable cotton silk blend saree with beautiful floral prints. Ideal for everyday elegance.',
    price: 3200,
    stock_count: 45,
    images: ['/images/products/cotton-silk.jpg'],
    category: 'Silk Sarees',
    mode_badges: ['A', 'B', 'C'],
    sku: 'SS-CS-003',
    rating: 4.4,
    review_count: 8,
    is_active: true,
  },
  {
    id: 'prod-004',
    merchant_id: 'merchant-1',
    merchant_name: 'Samskruti Silks',
    name: 'Handloom Silk Dupatta',
    description: 'Pure handloom silk dupatta with intricate thread work. Available in multiple colors.',
    price: 2400,
    stock_count: 60,
    images: ['/images/products/dupatta.jpg'],
    category: 'Accessories',
    mode_badges: ['A', 'B', 'C'],
    sku: 'SS-HD-004',
    rating: 4.3,
    review_count: 12,
    is_active: true,
  },
  // Pastry Cafe Products
  {
    id: 'prod-005',
    merchant_id: 'merchant-3',
    merchant_name: 'The Pastry Cafe',
    name: 'Belgian Chocolate Truffle Pastry',
    description: 'Rich Belgian chocolate truffle pastry with layers of dark chocolate ganache and moist chocolate sponge.',
    price: 180,
    stock_count: 24,
    images: ['/images/products/chocolate-truffle.jpg'],
    category: 'Pastries',
    mode_badges: ['A', 'C'],
    sku: 'PC-P-001',
    rating: 4.9,
    review_count: 45,
    is_active: true,
  },
  {
    id: 'prod-006',
    merchant_id: 'merchant-3',
    merchant_name: 'The Pastry Cafe',
    name: 'Red Velvet Cake (1 Kg)',
    description: 'Classic red velvet cake with cream cheese frosting. Perfect for celebrations.',
    price: 1200,
    stock_count: 10,
    images: ['/images/products/red-velvet.jpg'],
    category: 'Cakes',
    mode_badges: ['A', 'C'],
    sku: 'PC-CAKE-002',
    rating: 4.7,
    review_count: 32,
    is_active: true,
  },
  {
    id: 'prod-007',
    merchant_id: 'merchant-3',
    merchant_name: 'The Pastry Cafe',
    name: 'Mixed Fruit Croissant',
    description: 'Buttery croissant filled with fresh seasonal fruits and cream.',
    price: 150,
    stock_count: 30,
    images: ['/images/products/croissant.jpg'],
    category: 'Bakery',
    mode_badges: ['A', 'C'],
    sku: 'PC-B-003',
    rating: 4.5,
    review_count: 18,
    is_active: true,
  },
  // flowers2u Products
  {
    id: 'prod-008',
    merchant_id: 'merchant-4',
    merchant_name: 'flowers2u',
    name: 'Mixed Roses Bouquet (24 Roses)',
    description: 'Beautiful bouquet of 24 mixed-color roses, professionally arranged and wrapped.',
    price: 850,
    stock_count: 50,
    images: ['/images/products/roses.jpg'],
    category: 'Bouquets',
    mode_badges: ['A', 'B'],
    sku: 'F2U-001',
    rating: 4.6,
    review_count: 28,
    is_active: true,
  },
  {
    id: 'prod-009',
    merchant_id: 'merchant-4',
    merchant_name: 'flowers2u',
    name: 'Festival Flower Pack (Marigold)',
    description: 'Fresh marigold garlands and loose flowers for festivals and decorations.',
    price: 350,
    stock_count: 100,
    images: ['/images/products/marigold.jpg'],
    category: 'Festival Flowers',
    mode_badges: ['A', 'B'],
    sku: 'F2U-002',
    rating: 4.2,
    review_count: 14,
    is_active: true,
  },
  // Sanjana Apparels Products
  {
    id: 'prod-010',
    merchant_id: 'merchant-7',
    merchant_name: 'Sanjana Apparels (India)',
    name: "Women's Cotton Kurti - Printed",
    description: 'Comfortable cotton kurti with modern prints. Available in sizes S to XL.',
    price: 699,
    stock_count: 80,
    images: ['/images/products/kurti.jpg'],
    category: "Women's Wear",
    mode_badges: ['A', 'B', 'C'],
    sku: 'SA-WW-001',
    rating: 4.1,
    review_count: 9,
    is_active: true,
  },
  {
    id: 'prod-011',
    merchant_id: 'merchant-7',
    merchant_name: 'Sanjana Apparels (India)',
    name: "Men's Casual Shirt - Linen Blend",
    description: 'Breathable linen blend shirt perfect for Bangalore weather.',
    price: 899,
    stock_count: 55,
    images: ['/images/products/shirt.jpg'],
    category: "Men's Wear",
    mode_badges: ['A', 'B', 'C'],
    sku: 'SA-MW-002',
    rating: 4.3,
    review_count: 11,
    is_active: true,
  },
  // Madhumathi Ethnic Products
  {
    id: 'prod-012',
    merchant_id: 'merchant-8',
    merchant_name: "Madhumathi All-men's Ethnic",
    name: "Wedding Sherwani - Beige",
    description: 'Elegant beige wedding sherwani with gold embroidery. Premium fabric with lining.',
    price: 8500,
    stock_count: 20,
    images: ['/images/products/sherwani.jpg'],
    category: "Men's Ethnic",
    mode_badges: ['A', 'B', 'C'],
    sku: 'MA-001',
    rating: 4.7,
    review_count: 6,
    is_active: true,
  },
  {
    id: 'prod-013',
    merchant_id: 'merchant-8',
    merchant_name: "Madhumathi All-men's Ethnic",
    name: 'Cotton Kurta Pyjama Set - White',
    description: 'Classic white cotton kurta pyjama set. Comfortable and breathable.',
    price: 1499,
    stock_count: 40,
    images: ['/images/products/kurta-set.jpg'],
    category: "Men's Ethnic",
    mode_badges: ['A', 'B', 'C'],
    sku: 'MA-002',
    rating: 4.4,
    review_count: 14,
    is_active: true,
  },
];

export const ORDERS: Order[] = [
  {
    id: 'order-1',
    order_id: 'PM-20260530-001',
    user_id: 'cust-001',
    status: 'in_transit',
    total: 4891,
    delivery_fee: 95,
    subtotal: 4700,
    items: [
      { id: 'item-1', product_name: 'Kanjivaram Silk Saree - Gold Zari', quantity: 1, unit_price: 2800, total_price: 2800 },
      { id: 'item-2', product_name: 'Silk Dupatta', quantity: 1, unit_price: 400, total_price: 400 },
      { id: 'item-3', product_name: 'Chocolate Truffle Pastry', quantity: 1, unit_price: 1500, total_price: 1500 },
    ],
    created_at: '2026-05-30T10:30:00Z',
    delivery_address: {
      id: 'addr-1',
      name: 'Priya Sharma',
      phone: '9999999999',
      line1: '42, Jayanagar 4th Block',
      line2: 'Near Jain Temple',
      city: 'Bangalore',
      pincode: '560011',
      is_default: true,
    },
    merchant_name: 'Samskruti Silks',
  },
  {
    id: 'order-2',
    order_id: 'PM-20260529-002',
    user_id: 'cust-001',
    status: 'delivered',
    total: 3500,
    delivery_fee: 70,
    subtotal: 3430,
    items: [
      { id: 'item-4', product_name: 'Mixed Roses Bouquet (24 Roses)', quantity: 1, unit_price: 850, total_price: 850 },
      { id: 'item-5', product_name: 'Belgian Chocolate Truffle Pastry', quantity: 2, unit_price: 180, total_price: 360 },
      { id: 'item-6', product_name: 'Cotton Kurta Pyjama Set', quantity: 1, unit_price: 1499, total_price: 1499 },
      { id: 'item-7', product_name: "Men's Casual Shirt - Linen Blend", quantity: 1, unit_price: 899, total_price: 899 },
    ],
    created_at: '2026-05-29T14:00:00Z',
    delivery_address: {
      id: 'addr-1',
      name: 'Priya Sharma',
      phone: '9999999999',
      line1: '42, Jayanagar 4th Block',
      line2: 'Near Jain Temple',
      city: 'Bangalore',
      pincode: '560011',
      is_default: true,
    },
    merchant_name: 'flowers2u',
  },
  {
    id: 'order-3',
    order_id: 'PM-20260528-003',
    user_id: 'cust-001',
    status: 'cancelled',
    total: 2400,
    delivery_fee: 70,
    subtotal: 2330,
    items: [
      { id: 'item-8', product_name: 'Handloom Silk Dupatta', quantity: 1, unit_price: 2400, total_price: 2400 },
    ],
    created_at: '2026-05-28T09:15:00Z',
    delivery_address: {
      id: 'addr-1',
      name: 'Priya Sharma',
      phone: '9999999999',
      line1: '42, Jayanagar 4th Block',
      line2: 'Near Jain Temple',
      city: 'Bangalore',
      pincode: '560011',
      is_default: true,
    },
    merchant_name: 'Samskruti Silks',
  },
];

export const CART_ITEMS: CartItem[] = [
  {
    id: 'cart-1',
    product_id: 'prod-001',
    merchant_id: 'merchant-1',
    merchant_name: 'Samskruti Silks',
    product_name: 'Kanjivaram Silk Saree - Gold Zari',
    price: 2800,
    quantity: 1,
    image: '/images/products/saree-1.jpg',
    mode: 'A',
  },
  {
    id: 'cart-2',
    product_id: 'prod-004',
    merchant_id: 'merchant-1',
    merchant_name: 'Samskruti Silks',
    product_name: 'Handloom Silk Dupatta',
    price: 400,
    quantity: 2,
    image: '/images/products/dupatta.jpg',
    mode: 'A',
  },
  {
    id: 'cart-3',
    product_id: 'prod-005',
    merchant_id: 'merchant-3',
    merchant_name: 'The Pastry Cafe',
    product_name: 'Belgian Chocolate Truffle Pastry',
    price: 180,
    quantity: 2,
    image: '/images/products/chocolate-truffle.jpg',
    mode: 'A',
  },
  {
    id: 'cart-4',
    product_id: 'prod-008',
    merchant_id: 'merchant-4',
    merchant_name: 'flowers2u',
    product_name: 'Mixed Roses Bouquet (24 Roses)',
    price: 850,
    quantity: 1,
    image: '/images/products/roses.jpg',
    mode: 'A',
  },
];

export const ADDRESSES: Address[] = [
  {
    id: 'addr-1',
    name: 'Home',
    phone: '9999999999',
    line1: '42, Jayanagar 4th Block',
    line2: 'Near Jain Temple, 2nd Main Road',
    city: 'Bangalore',
    pincode: '560011',
    landmark: 'Near Jain Temple',
    is_default: true,
  },
  {
    id: 'addr-2',
    name: 'Office',
    phone: '9999999999',
    line1: 'MG Road, Unity Building',
    line2: '5th Floor, Suite 502',
    city: 'Bangalore',
    pincode: '560001',
    landmark: 'Opposite MG Road Metro',
    is_default: false,
  },
];

export const ORDER_STATUSES = [
  { key: 'confirmed', label: 'Order Confirmed', date: '2026-05-30T10:35:00Z' },
  { key: 'picked_up', label: 'Picked Up', date: '2026-05-30T11:20:00Z' },
  { key: 'consolidated', label: 'Consolidated', date: '2026-05-30T12:00:00Z' },
  { key: 'in_transit', label: 'In Transit', date: '2026-05-30T12:45:00Z' },
];

export function getMerchantsByMarket(marketSlug: string): Merchant[] {
  const market = MARKETS.find(m => m.slug === marketSlug);
  if (!market) return [];
  return MERCHANTS.filter(m => m.market_id === market.id);
}

export function getProductsByMerchant(merchantId: string): Product[] {
  return PRODUCTS.filter(p => p.merchant_id === merchantId);
}

export function getMerchant(id: string): Merchant | undefined {
  return MERCHANTS.find(m => m.id === id);
}

export function getProduct(id: string): Product | undefined {
  return PRODUCTS.find(p => p.id === id);
}

export function getMerchantBySlug(slug: string): Merchant | undefined {
  return MERCHANTS.find(m => m.slug === slug);
}

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find(p => p.id === id);
}
